print("Привет програмист!")
print(2+2)
print(10/3)
name = "Vladimir"
print(name)
v = int(input("Введите число от 1 до 10: "))
print(v)
print(v+10)
name = input("Введите ваше имя: ")
print(f"Привет, {name}! Как дела ?")
print(float("1"))
print(int(float("2.5")))
print(bool(1))
print(bool(''))
print(bool(0))
